// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4carslp_cv_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4eightschools_sim_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4sparsecar_slp_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4carslp_cv_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4carslp_cv_mod, 0},
    {"_rcpp_module_boot_stan_fit4eightschools_sim_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4eightschools_sim_mod, 0},
    {"_rcpp_module_boot_stan_fit4sparsecar_slp_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4sparsecar_slp_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_AXEexamples(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
